// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using tt_apps_srs.Models;

namespace tt_apps_srs.Migrations
{
    [DbContext(typeof(tt_apps_srs_db_context))]
    partial class tt_apps_srs_db_contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("tt_apps_srs.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(4);

                    b.Property<string>("add_ln_1")
                        .IsRequired()
                        .HasMaxLength(1024);

                    b.Property<string>("addr_ln_2")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("tt_apps_srs.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("UrlCode")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("IX_Tenant_Name");

                    b.HasIndex("UrlCode")
                        .IsUnique()
                        .HasName("IX_Tenant_UrlCode");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("tt_apps_srs.Models.TenantProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("TenantProperties");
                });

            modelBuilder.Entity("tt_apps_srs.Models.TenantStore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("StoreId");

                    b.Property<Guid>("TenantId");

                    b.HasKey("Id");

                    b.ToTable("TenantStores");
                });
#pragma warning restore 612, 618
        }
    }
}
